version: '3.3'

services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - mediawiki-data:/var/www/html
    environment:
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_USER=wiki
      - MEDIAWIKI_DB_PASSWORD=wikiP@ssword
      - MEDIAWIKI_DB_NAME=wikidb
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=wikiP@ssword
      - MYSQL_ROOT_PASSWORD=wikiRootP@ssword
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mediawiki-data:
  mariadb-data:
