version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mediawiki-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test123  # Укажите свой пароль
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: Test123  # Укажите свой пароль
    volumes:
      - db_data:/var/lib/mysql

  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_USER: wiki
      MEDIAWIKI_DB_PASSWORD: WikiP@ssw0rd
      MEDIAWIKI_DB_NAME: mediawiki
    volumes:
      - mediawiki_images:/var/www/html/images

volumes:
  db_data:
  mediawiki_images:
